version: '3'
services:
  postgres:
    image: postgres:13.4
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app

  app:
    build:
      context: ./
      dockerfile: ./app.Dockerfile    
    command: bash -c "npm i && npm run dev"
    volumes:
      - ./app:/home/app
    depends_on:
      - postgres
    environment:
      DATABASE: postgresql://app:app@postgres/app
      NODE_ENV: development
      NODE_OPTIONS: --trace-warnings
